dist: xenial

language:
  - groovy
  - python

python:
  - 2.7

jdk:
  - openjdk8

before_install:
  - sudo pip install pandas
  - sudo pip install 'biopython==1.76'
  
script:
  - cd src/ 
  - travis_wait groovy -cp . BuildDatabase.groovy --no2fix
