dist: xenial

language:
  - groovy
  - python
  
jdk:
  - openjdk8

before_install:
  - sudo pip install pandas
  - sudo pip install biopython
  
script:
  - cd src/ 
  - travis_wait groovy -cp . BuildDatabase.groovy --no2fix
